# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 16:37
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0038_auto_20160924_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(default=django.utils.crypto.get_random_string, max_length=255, verbose_name='Cart ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('expires', models.DateTimeField(verbose_name='Expiration date')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event', verbose_name='Event')),
            ],
        ),
    ]
