# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 10:47
from __future__ import unicode_literals

import pretix_cartshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_cartshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedcart',
            name='cart_id',
            field=models.CharField(default=pretix_cartshare.models.generate_cart_id, max_length=255, verbose_name='Cart ID'),
        ),
    ]
